version: '3.8'

services:
  backend:
    container_name: '${APP_NAME}_backend'
    build:
      context: .
      dockerfile: web/dockerfile
    volumes:
      - ./../app:/var/www/app
      - ./data/logs/nginx:/var/log/nginx
    ports:
      - '443:443'
      - '80:80'
    environment:
      PHP_IDE_CONFIG: 'serverName=${APP_DOMAIN}'
      APP_DOMAIN: '${APP_DOMAIN}'
    depends_on:
      - database
    extra_hosts:
      - host.docker.internal:host-gateway

  database:
    container_name: '${APP_NAME}_db'
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${APP_NAME}
      MYSQL_USER: ${APP_NAME}
      MYSQL_PASSWORD: ${APP_NAME}
      MYSQL_ROOT_PASSWORD: ${APP_NAME}
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - '3306:3306'

  maildev:
    container_name: '${APP_NAME}_mail'
    image: dominikserafin/maildev
    ports:
      - '9025:1025'
      - '9080:1080'

  adminer:
    image: adminer
    environment:
      ADMINER_DESIGN: nette
    ports:
      - '8666:8080'
